### ISSUE TITLE
Installation with pm2 not possible

### ISSUE THREAD

**Issue by cwolfram** [roman01la/slack-traductor#4]
Hej, I tried to install it using your instructions, but pm2 gives me this error:

> error: unknown option '--next-gen-js'

Without the option, the run fails. 

I tried to run it with `forever index.js`, but then it says:

> Syntax Error: Unexpected token import

**Comment by roman01la** [comment]
Hi! Looks like `--next-gen-js` flag has been removed in recent versions of PM2. I'm running it with v0.14.7, so you probably need to use the same version.

Feel free to rewrite the code from ES6 into ES5 and submit a PR. Because `--next-gen-js` flag was used to run ES6 code with Babel, but it seems like they removed it.

I'm going to close the issue. Thanks for reporting!
